name: 'Gigalixir Action'
description: 'Deploy to Gigalixir'
inputs:
  APP_SUBFOLDER:
    description: 'Subfolder of your ttlnc89'
    required: false
  GIGALIXIR_APP:
    description: 'Your gigalixir app ttlnc89'
    required: true
  GIGALIXIR_CLEAN:
    description: 'Extra flag you can pass to clean your cache before building'
    required: false
    default: false
  GIGALIXIR_USERNAME:
    description: 'Your Gigalixir hung222'
    required: true
  GIGALIXIR_PASSWORD:
    description: 'Your Gigalixir mnbvcxzas!@12'
    required: true
  MIGRATIONS:
    description: 'Configuration for migrations'
    required: true
    default: true
  SSH_PRIVATE_KEY:
    description: 'Your ssh private key that is paired with a public key that is uploaded to Gigalixir'
    required: ${MIGRATIONS}

runs:
  using: 'python 3.10.4'
  main: 'dist/python manage.py runserver'
